server:
  port: 8080

indexing-settings:
  sites:
    - url: http://www.playback.ru
      name: плэйбэк.ру
    - url: https://www.lutherancathedral.ru
      name: собор.ру
    - url: https://ipfran.ru
      name: ипфран.ру


spring:
  datasource:
    username: root
    password: 111www111
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC& cachePrepStmts=true&useServerPrepStmts=true&rewriteBatchedStatements=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      jdbc:
        batch_size: 1500
      order_insets: true
      ddl-auto: update
    show-sql: true









