server:
  port: 8080

indexing-settings:
  sites:
    - url: https://www.svetlovka.ru
      name: светловка.ру
    - url: https://www.lutherancathedral.ru
      name: собор.ру
    - url: https://ipfran.ru
      name: ипфран.ру


spring:
  datasource:
    username: root
    password: 111www111
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC& cachePrepStmts=true&useServerPrepStmts=true&rewriteBatchedStatements=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      jdbc:
        batch_size: 1500
      order_insets: true
      ddl-auto: update
    show-sql: true

jsoup-properties:
  user-agent: Mozilla/5.0 (Windows; U; WindowsNT 5.1; en-US; rvl.8.1.6.) Gecko/20070725 Firefox/2.0.0.6.
  referrer: http://www.google.com







